---
services:
  sml2mqtt:
    image: spacemanspiff2007/sml2mqtt
    container_name: sml2mqtt
    init: true
    restart: unless-stopped
    mem_limit: 64m
    volumes:
      # Subdirectory ./data contains config.yml and log files
      - "./data:/sml2mqtt"
    devices:
      # Replace with the location to your device
      - /dev/serial/by-id/<ID-OF-SERIAL-DEVICE-TO-METER>
    environment:
      # Numerical UID of the owner of log files
      USER_ID: 1000

      # Numerical GID of the serial device, as returned by
      # `stat --printf=%g /dev/serial/by-id/<ID-OF-SERIAL-DEVICE-TO-METER>`
      GROUP_ID: 20
